---

- hosts: [ "GRUPPOCENTOS", "GRUPPOUBUNTU" ]
  become: true

  tasks:
  - name: test install apache and php plus update cache
    package:
      name: 
        - "{{ http_server }}"
        - "{{ php }}"
      state: latest
      update_cache: true
  - name: copy index.html
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
  - name: install unzip
    package:
      name: unzip
  - name: scarica e unzippa terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/bin
      remote_src: yes
      owner: root
      group: root
      mode: 0755
