- name: install unzip
  package:
    name: unzip

- name: scarica e unzippa terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
    dest: /usr/bin
    remote_src: yes
    owner: root
    group: root
    mode: 0755
